# Generated by Django 5.1 on 2024-08-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
